refactor: extract IntakeEventCounter and FallenBehindManager to gossip module
hiero-ledger/hiero-consensus-node pull request #15986
Opened 2024-10-15 14:26 UTC by mustafauzunn

**Description**:
 
Extraction of IntakeEventCounter and FallenBehindManager interfaces to gossip module.
Extraction of DefaultIntakeEventCounter to gossip-impl module.
Move Address, AddressBook, AddressBookIterator and SerializableX509Certificate to swirlds-common module.

**Related issue(s)**:

Fixes 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-10-16 20:04 UTC, rbarkerSL requested changes

2024-10-16 20:04 UTC, rbarkerSL commented on hedera-node/hedera-addressbook-service-impl/build.gradle.kts
> +    requires("com.swirlds.common")
Is this for a new publish group? I didn't think we were publishing anything new to com.swirlds.*

2024-10-16 20:04 UTC, rbarkerSL commented on platform-sdk/consensus-gossip-impl/src/main/java/module-info.java
> +    requires transitive com.swirlds.common;
Is this for a new publish group? I didn't think we were publishing anything new to com.swirlds.*

2024-10-16 20:04 UTC, rbarkerSL commented on platform-sdk/consensus-gossip/src/main/java/module-info.java
> +    requires transitive com.swirlds.common;
Is this for a new publish group? I didn't think we were publishing anything new to com.swirlds.*

2024-10-17 17:11 UTC, litt3 commented on platform-sdk/swirlds-common/src/main/java/com/swirlds/common/AddressBook.java
> +    public static String addressBookConfigText(@NonNull final AddressBook addressBook) {
Is the idea that this should be replaced with a call to `AddressBookUtils` after that file has also been moved? If so, this method should probably be private, and have a FUTURE WORK note explaining the future intention

2024-10-18 13:06 UTC, litt3 submitted a review, later dismissed
lgtm

2024-10-18 20:16 UTC, rbarkerSL approved these changes
Review applies to

- hedera-node/hedera-addressbook-service-impl/build.gradle.kts
- platform-sdk/consensus-gossip-impl/src/main/java/module-info.java
- platform-sdk/consensus-gossip/src/main/java/module-info.java
- platform-sdk/swirlds-platform-core/src/main/java/module-info.java
- platform-sdk/swirlds-platform-core/src/testFixtures/java/module-info.java
- platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/module-info.java

LGTM

2024-10-19 16:33 UTC, jeromy-cannon approved these changes

2024-10-22 14:35 UTC, poulok requested changes
I have a couple questions/concerns:

1. What issue is this fixing?
2. Why is this moving the AddressBook class that is currently being removed from the platform?
3. I think this will conflict with a large refactor PR from @anthony-swirldslabs that is critical to the TSS Roster project. Is it necessary that this is done now?

2024-10-22 15:11 UTC, poulok commented
>This PR is part of the platform modularization effort

Ah, understood. We usually keep a 1:1 ratio of PRs to tickets, but if the decision is to depart from that approach, please at least reference the ticket this PR supports in the description to provide more context to reviewers.

>Moved Address, AddressBook, AddressBookIterator and SerializableX509Certificate to the swirlds-common module because they are currently in the platform-core module.
DefaultIntakeEventCounter we move to new module that needs AddressBook for example and if we don't move AddressBook to some other module we will have circular dependencies. We want small PRs and this is the approach I am using

Makes sense, except for the point below.

>I think AddressBook is used in many places currently and I think we can't modularise the codebase without these classes.

There is [this open PR](https://github.com/hashgraph/hedera-services/pull/16026) that goes a very long way to eliminating AddressBook from the platform. More PRs will follow to cleanup the remaining references. We must deconflict these PRs. In my opinion, these other PRs are higher priority as they are required to get TSS Rosters delivered, which unblocks the TSS Base Service integration testing work. All of this is required to deliver Block Nodes.

2025-04-24 08:18 UTC, IvanKavaldzhiev commented
Closing since this PR is now obsolete.

2025-04-24 08:18 UTC, closed without merging